domain_name="kobby.cloud"
key_name="mkdirprince-key-pair.pem"
vpc_id="vpc-013a1615e7f26dd6b"
subnet_id="subnet-00cc67c234c0cd1bc"
key_path="/Users/wilson/tech_journey/HNG_internship/mkdirprince-key-pair.pem.pem"
admin_email="mkdirprince@gmail.com"
git_repo_url="https://github.com/mkdirprince/infra-stage4.git"
git_branch="main"
