- name: Clone application repository
  git:
    repo: "https://github.com/mkdirprince/DevOps-Stage-4.git"
    dest: "/home/ubuntu/app"
    version: main

- name: stop running docker containers
  shell: docker-compose down
  args:
    chdir: /home/ubuntu/app

- name: Start application with Docker Compose
  shell: docker-compose up -d --build
  args:
    chdir: /home/ubuntu/app
